[env:uno]
platform = atmelavr
board = uno
; upload_port = /dev/ttyACM0
framework = arduino
monitor_speed = 9600

include_dir =
    include/

src_dir =
    src/

lib_deps =
    arduino-libraries/Servo @ 1.2.1